// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/matjam/maxbbs/ent/message"
	"github.com/matjam/maxbbs/ent/predicate"
	"github.com/matjam/maxbbs/ent/user"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetCreated sets the "created" field.
func (mu *MessageUpdate) SetCreated(t time.Time) *MessageUpdate {
	mu.mutation.SetCreated(t)
	return mu
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCreated(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetCreated(*t)
	}
	return mu
}

// SetUpdated sets the "updated" field.
func (mu *MessageUpdate) SetUpdated(t time.Time) *MessageUpdate {
	mu.mutation.SetUpdated(t)
	return mu
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableUpdated(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetUpdated(*t)
	}
	return mu
}

// SetDeleted sets the "deleted" field.
func (mu *MessageUpdate) SetDeleted(t time.Time) *MessageUpdate {
	mu.mutation.SetDeleted(t)
	return mu
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableDeleted(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetDeleted(*t)
	}
	return mu
}

// SetSubject sets the "subject" field.
func (mu *MessageUpdate) SetSubject(s string) *MessageUpdate {
	mu.mutation.SetSubject(s)
	return mu
}

// SetBody sets the "body" field.
func (mu *MessageUpdate) SetBody(s string) *MessageUpdate {
	mu.mutation.SetBody(s)
	return mu
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (mu *MessageUpdate) SetAuthorID(id int) *MessageUpdate {
	mu.mutation.SetAuthorID(id)
	return mu
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (mu *MessageUpdate) SetNillableAuthorID(id *int) *MessageUpdate {
	if id != nil {
		mu = mu.SetAuthorID(*id)
	}
	return mu
}

// SetAuthor sets the "author" edge to the User entity.
func (mu *MessageUpdate) SetAuthor(u *User) *MessageUpdate {
	return mu.SetAuthorID(u.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (mu *MessageUpdate) ClearAuthor() *MessageUpdate {
	mu.mutation.ClearAuthor()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.Subject(); ok {
		if err := message.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Message.subject": %w`, err)}
		}
	}
	if v, ok := mu.mutation.Body(); ok {
		if err := message.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Message.body": %w`, err)}
		}
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Created(); ok {
		_spec.SetField(message.FieldCreated, field.TypeTime, value)
	}
	if value, ok := mu.mutation.Updated(); ok {
		_spec.SetField(message.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := mu.mutation.Deleted(); ok {
		_spec.SetField(message.FieldDeleted, field.TypeTime, value)
	}
	if value, ok := mu.mutation.Subject(); ok {
		_spec.SetField(message.FieldSubject, field.TypeString, value)
	}
	if value, ok := mu.mutation.Body(); ok {
		_spec.SetField(message.FieldBody, field.TypeString, value)
	}
	if mu.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetCreated sets the "created" field.
func (muo *MessageUpdateOne) SetCreated(t time.Time) *MessageUpdateOne {
	muo.mutation.SetCreated(t)
	return muo
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCreated(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetCreated(*t)
	}
	return muo
}

// SetUpdated sets the "updated" field.
func (muo *MessageUpdateOne) SetUpdated(t time.Time) *MessageUpdateOne {
	muo.mutation.SetUpdated(t)
	return muo
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableUpdated(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetUpdated(*t)
	}
	return muo
}

// SetDeleted sets the "deleted" field.
func (muo *MessageUpdateOne) SetDeleted(t time.Time) *MessageUpdateOne {
	muo.mutation.SetDeleted(t)
	return muo
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableDeleted(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetDeleted(*t)
	}
	return muo
}

// SetSubject sets the "subject" field.
func (muo *MessageUpdateOne) SetSubject(s string) *MessageUpdateOne {
	muo.mutation.SetSubject(s)
	return muo
}

// SetBody sets the "body" field.
func (muo *MessageUpdateOne) SetBody(s string) *MessageUpdateOne {
	muo.mutation.SetBody(s)
	return muo
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (muo *MessageUpdateOne) SetAuthorID(id int) *MessageUpdateOne {
	muo.mutation.SetAuthorID(id)
	return muo
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableAuthorID(id *int) *MessageUpdateOne {
	if id != nil {
		muo = muo.SetAuthorID(*id)
	}
	return muo
}

// SetAuthor sets the "author" edge to the User entity.
func (muo *MessageUpdateOne) SetAuthor(u *User) *MessageUpdateOne {
	return muo.SetAuthorID(u.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (muo *MessageUpdateOne) ClearAuthor() *MessageUpdateOne {
	muo.mutation.ClearAuthor()
	return muo
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.Subject(); ok {
		if err := message.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Message.subject": %w`, err)}
		}
	}
	if v, ok := muo.mutation.Body(); ok {
		if err := message.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Message.body": %w`, err)}
		}
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Created(); ok {
		_spec.SetField(message.FieldCreated, field.TypeTime, value)
	}
	if value, ok := muo.mutation.Updated(); ok {
		_spec.SetField(message.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := muo.mutation.Deleted(); ok {
		_spec.SetField(message.FieldDeleted, field.TypeTime, value)
	}
	if value, ok := muo.mutation.Subject(); ok {
		_spec.SetField(message.FieldSubject, field.TypeString, value)
	}
	if value, ok := muo.mutation.Body(); ok {
		_spec.SetField(message.FieldBody, field.TypeString, value)
	}
	if muo.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
