// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/matjam/maxbbs/ent/message"
	"github.com/matjam/maxbbs/ent/user"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
}

// SetCreated sets the "created" field.
func (mc *MessageCreate) SetCreated(t time.Time) *MessageCreate {
	mc.mutation.SetCreated(t)
	return mc
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (mc *MessageCreate) SetNillableCreated(t *time.Time) *MessageCreate {
	if t != nil {
		mc.SetCreated(*t)
	}
	return mc
}

// SetUpdated sets the "updated" field.
func (mc *MessageCreate) SetUpdated(t time.Time) *MessageCreate {
	mc.mutation.SetUpdated(t)
	return mc
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (mc *MessageCreate) SetNillableUpdated(t *time.Time) *MessageCreate {
	if t != nil {
		mc.SetUpdated(*t)
	}
	return mc
}

// SetDeleted sets the "deleted" field.
func (mc *MessageCreate) SetDeleted(t time.Time) *MessageCreate {
	mc.mutation.SetDeleted(t)
	return mc
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (mc *MessageCreate) SetNillableDeleted(t *time.Time) *MessageCreate {
	if t != nil {
		mc.SetDeleted(*t)
	}
	return mc
}

// SetSubject sets the "subject" field.
func (mc *MessageCreate) SetSubject(s string) *MessageCreate {
	mc.mutation.SetSubject(s)
	return mc
}

// SetBody sets the "body" field.
func (mc *MessageCreate) SetBody(s string) *MessageCreate {
	mc.mutation.SetBody(s)
	return mc
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (mc *MessageCreate) SetAuthorID(id int) *MessageCreate {
	mc.mutation.SetAuthorID(id)
	return mc
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (mc *MessageCreate) SetNillableAuthorID(id *int) *MessageCreate {
	if id != nil {
		mc = mc.SetAuthorID(*id)
	}
	return mc
}

// SetAuthor sets the "author" edge to the User entity.
func (mc *MessageCreate) SetAuthor(u *User) *MessageCreate {
	return mc.SetAuthorID(u.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mc *MessageCreate) Mutation() *MessageMutation {
	return mc.mutation
}

// Save creates the Message in the database.
func (mc *MessageCreate) Save(ctx context.Context) (*Message, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MessageCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MessageCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MessageCreate) defaults() {
	if _, ok := mc.mutation.Created(); !ok {
		v := message.DefaultCreated()
		mc.mutation.SetCreated(v)
	}
	if _, ok := mc.mutation.Updated(); !ok {
		v := message.DefaultUpdated()
		mc.mutation.SetUpdated(v)
	}
	if _, ok := mc.mutation.Deleted(); !ok {
		v := message.DefaultDeleted()
		mc.mutation.SetDeleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MessageCreate) check() error {
	if _, ok := mc.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Message.created"`)}
	}
	if _, ok := mc.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "Message.updated"`)}
	}
	if _, ok := mc.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New(`ent: missing required field "Message.deleted"`)}
	}
	if _, ok := mc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Message.subject"`)}
	}
	if v, ok := mc.mutation.Subject(); ok {
		if err := message.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Message.subject": %w`, err)}
		}
	}
	if _, ok := mc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Message.body"`)}
	}
	if v, ok := mc.mutation.Body(); ok {
		if err := message.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Message.body": %w`, err)}
		}
	}
	return nil
}

func (mc *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.Created(); ok {
		_spec.SetField(message.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := mc.mutation.Updated(); ok {
		_spec.SetField(message.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := mc.mutation.Deleted(); ok {
		_spec.SetField(message.FieldDeleted, field.TypeTime, value)
		_node.Deleted = value
	}
	if value, ok := mc.mutation.Subject(); ok {
		_spec.SetField(message.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := mc.mutation.Body(); ok {
		_spec.SetField(message.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if nodes := mc.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_messages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	builders []*MessageCreate
}

// Save creates the Message entities in the database.
func (mcb *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Message, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
